# File: /ahorrinbot/ahorrinbot/src/services/openai_service.py

import openai
from src.config import OPENAI_API_KEY

# Initialize OpenAI API with the provided API key
openai.api_key = OPENAI_API_KEY

def generate_response(prompt: str) -> str:
    """
    Sends a prompt to the OpenAI API and retrieves the generated response.

    Args:
        prompt (str): The input text prompt to send to the OpenAI model.

    Returns:
        str: The response generated by the OpenAI model.
    """
    try:
        # Call the OpenAI API with the specified prompt
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",  # Specify the model to use
            messages=[{"role": "user", "content": prompt}],
            max_tokens=150  # Limit the number of tokens in the response
        )
        # Extract and return the content of the response
        return response['choices'][0]['message']['content'].strip()
    except Exception as e:
        # Handle any exceptions that occur during the API call
        print(f"Error communicating with OpenAI API: {e}")
        return "Error generating response."  # Return a default error message

# Additional functions for interacting with OpenAI can be added here
# For example, functions for different types of prompts or models can be implemented.